import type {NextPage} from 'next'
import Head from 'next/head'
import {Events, Feed, Header, Sidebar} from "../components";
import {data} from "../constants";

const Home: NextPage = () => {
    return (
        <div className={'h-screen bg-primary text-white overflow-hidden'}>
            <Head>
                <title>Home - Facebook</title>
                <meta name="description" content="Generated by create next app"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>

            <Header {...data.header}/>
            <div className={'h-full w-full pt-4 flex'}>
                <aside className={'hidden flex-1 scroll-y-hide sm:inline-block sm:basis-1/4 md:basis-1/5'}>
                    <Sidebar {...data.sidebar}/>
                </aside>
                <main className={'flex-1 basis-full scroll-y-hide sm:basis-3/4 md:basis-3/5'}>
                    <Feed {...data.feed}/>
                </main>
                <aside className={'hidden flex-1 scroll-y-hide bg-blue-500 lg:inline-block lg:basis-1/5'}>
                    <Events/>
                </aside>
            </div>
        </div>
    )
}

export default Home
