import Head from 'next/head';
import {Anek_Latin} from '@next/font/google';
import {FeedInput, Navigation, Post, SidebarLeft, SidebarRight, Stories} from "../components";
import React from "react";

const anek = Anek_Latin({
    weight: ['100', '300', '400', '500', '600', '700'],
    style: ['normal'],
    subsets: ['latin'],
})

export default function Home() {
    return (
        <>
            <Head>
                <title>FacebookV5</title>
                <meta name="description" content="Generated by create next app"/>
                <meta name="viewport" content="width=device-width, initial-scale=1"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>

            <header className={`${anek.className} py-2 px-4 min-h-24 bg-primary drop-shadow-md`}>
                <Navigation/>
                {/*<hr className={`w-full h-[1px] border-none outline-none mt-5 mb-7 bg-secondary`}/>*/}
            </header>
            <main className={`${anek.className} max-w-[1650px] mx-auto bg-primary max-h-screen px-1 flex flex-1 overflow-y-hidden md:space-x-4`}>
                <SidebarLeft/>
                <article className={`flex flex-1 flex-col min-h-screen overflow-y-scroll scrollbar-hide md:basis-3/4 bg-red-3000`}>
                    <Stories/>
                    <FeedInput/>
                    <Post/>
                </article>
                <SidebarRight/>
            </main>
        </>
    )
}
