import type {NextPage} from 'next'
import Head from 'next/head'
import {Feed, LeftWidgets, Navbar, RightWidgets} from "../layouts";

const Home: NextPage = () => {
    return (
        <div className={'h-screen'}>
            <Head>
                <title>Facebook</title>
                <meta name="description" content="Generated by create next app"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>

            <Navbar/>
            {/*<div className={'absolute top-16 left-3 right-3 h-[1px] bg-inputColor'}/>*/}
            <main className={'h-full w-full max-w-[1536px] mx-auto pt-20 px-1 flex sm:space-x-3 bg-sky-200/0 '}>
                <LeftWidgets/>
                <Feed/>
                <RightWidgets/>
            </main>
        </div>
    )
}

export default Home
